version: "3.9"

services:
    app:
        build: .
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    web:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-app
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "8081:80"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
